
#########################################################################################################################################################
[Pathway]

[Pathway.observations-dir]

ground_observation_data_dir  = '/my-projects/Projects/MLCNN_PM25_2021/data/' 
geophysical_species_data_dir = '/my-projects/Projects/PM25_Speices_DL_2023/data/monthly_geophysical/'
geophysical_biases_data_dir  = '/my-projects/Projects/PM25_Speices_DL_2023/data/monthly_biases/'

[Pathway.TrainingModule-dir]

training_infile = '/my-projects/Projects/MLCNN_PM25_2021/data/CNN_Training_data_NCWH_11x11_channel33_start1998_InterpolateVariables_GFED4EMI.npy'
model_outdir    = '/my-projects/Projects/MLCNN_PM25_2021/code/Training_Testing_Evaluation/'

[Pathway.Results-dir]

txt_outdir   = '/my-projects/Projects/MLCNN_PM25_2021/code/Training_Testing_Evaluation/'
[Pathway.Config-outdir]

Config_outdir = '/my-projects/Projects/MLCNN_PM25_2021/code/Training_Testing_Evaluation/'

[Pathway.Figures-dir]

Scatter_plots_outdir = '/my-projects/Projects/PM25_Speices_DL_2023/code/Training_Evaluation_Estimation/'
Loss_Accuracy_outdir = '/my-projects/Projects/PM25_Speices_DL_2023/code/Training_Evaluation_Estimation/'
#########################################################################################################################################################
[Training-Settings]

[Training-Settings.identity]

version      = 'v1.0.0'
special_name = '_ResNet_test_epoch30'

[Training-Settings.hyper-parameters]

epoch         = 30
batchsize     = 512
learning_rate = 0.01
lr_strategy   = ''

channel_names = ['EtaAOD_Bias','EtaCoastal','EtaMixing','EtaSGAOD_Bias','EtaSGTOPO_Bias',
                'AOD','ETA',
                'GC_PM25','GC_NH4','GC_SO4','GC_NIT','GC_SOA','GC_OC','GC_BC','GC_DST','GC_SSLT',
                'GeoPM25','Lat','Lon',
                'Landtype','Elevation',
                'BC_Emi','OC_Emi','DST_Emi','SSLT_Emi',
                'PBLH','T2M','V10M','U10M','RH',
                'Population',
                'SitesNumber',
                'GFED4_TOTL_DM_Emi']
channel_index = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,20,21,22,23,24,25,26,27,28,29]

[Training-Settings.learning-objective]

bias = true   # learning objectives: bias = ground-based species observation - geophysical species concentration estimation
normalize_species = false
absolute_species  = false 
log_species = false


#########################################################################################################################################################

[Spatial-CrossValidation]

Combine_with_geophysical = true
Spatial_CrossValidation_Switch      = true
Spatial_CV_LossAccuracy_plot_Switch = true

[Spatial-CrossValidation.Training_Settings]

kfold   = 10
repeats = 1
beginyears = [2000, 2005, 2010, 2015]
endyears   = [2004, 2009, 2014, 2019]

MultiyearForMultiAreasList = [['NA'],['NA'],['NA','EU'],['NA','EU','AS','GL']]## Each model test on which areas

Area_beginyears.NA = 2001
Area_beginyears.EU = 2010
Area_beginyears.AS = 2015
Area_beginyears.GL = 2015

[Spatial-CrossValidation.Visualization_Settings]

regression_plot_switch = true

[Spatial-CrossValidation.Forced-Slope-Unity]

ForcedSlopeUnity = false # True: force the slope to unity and offset to zero with Training datasets
EachMonthForcedSlopeUnity = true # True: force the slope to unity and offset to zero by each year, each month; False: by each month, but all-year average 

