
#########################################################################################################################################################
[Pathway]

[Pathway.observations-dir]

ground_observation_data_dir  = '/my-projects/Projects/MLCNN_PM25_2021/data/monthly_observations/' 
ground_observation_data_infile = 'obsPM25_199801-201912_total-10870.npy'

geophysical_species_data_dir = '/my-projects/Projects/MLCNN_PM25_2021/data/monthly_geophysicalPM/'
geophysical_species_data_infile = 'geoPM25_199801-201912_total-10870.npy'

geophysical_biases_data_dir  = '/my-projects/Projects/MLCNN_PM25_2021/data/monthly_biases/'
geophysical_biases_data_infile = 'truedata_199801-201912_total-10870.npy'

population_data_dir  = '/my-projects/Projects/MLCNN_PM25_2021/data/monthly_population/'
population_data_infile = 'population_199801-201912_total-10870.npy'

[Pathway.TrainingModule-dir]

training_infile = '/my-projects/Projects/MLCNN_PM25_2021/data/CNN_Training_data_NCWH_11x11_channel31_start1998_1998-2019_10870sites_OldVersion-Geo-GC-OldMethods.npy'
model_outdir    = '/my-projects/Projects/MLCNN_PM25_2021/code/Training_Testing_Evaluation/'

[Pathway.Results-dir]

txt_outdir   = '/my-projects/Projects/MLCNN_PM25_2021/code/Training_Testing_Evaluation/'
[Pathway.Config-outdir]

Config_outdir = '/my-projects/Projects/MLCNN_PM25_2021/code/Training_Testing_Evaluation/'

[Pathway.Figures-dir]

Scatter_plots_outdir = '/my-projects/Projects/MLCNN_PM25_2021/code/Training_Testing_Evaluation/'
Loss_Accuracy_outdir = '/my-projects/Projects/MLCNN_PM25_2021/code/Training_Testing_Evaluation/'

#########################################################################################################################################################
[Training-Settings]


[Training-Settings.identity]

version      = 'v2.0.0'
special_name = '_Optiaml_Model_OldVersion-Geo-GC-OldMethods'
total_sites_number = 10870

[Training-Settings.hyper-parameters]

epoch         = 70
batchsize     = 128

channel_names = ['EtaAOD_Bias','EtaCoastal','EtaMixing','EtaSGAOD_Bias','EtaSGTOPO_Bias',
                'AOD','ETA',
                'GC_PM25','GC_NH4','GC_SO4','GC_NIT','GC_SOA','GC_OC','GC_BC','GC_DST','GC_SSLT',
                'GeoPM25','Lat','Lon',
                'Landtype','Elevation',
                'BC_Emi','OC_Emi','DST_Emi','SSLT_Emi',
                'PBLH','T2M','V10M','U10M','RH',
                'Population',
                'SitesNumber',
                'GFED4_TOTL_DM_Emi']
channel_index = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,20,21,22,23,24,25,26,27,28,29]#[6,17,20,21,22,23,24,25,26,27,28,29]#
weight_decay  = 0

[Training-Settings.learning_rate]

learning_rate0 = 0.01

ExponentialLR.Settings = false
ExponentialLR.gamma    = 0.9

CosineAnnealingLR.Settings = true
CosineAnnealingLR.T_max = 10
CosineAnnealingLR.eta_min = 1e-8

CosineAnnealingRestartsLR.Settings = false
CosineAnnealingRestartsLR.T_0      = 10
CosineAnnealingRestartsLR.T_mult   = 2
CosineAnnealingRestartsLR.eta_min = 0

[Training_Settings.activation_func]

activation_func_name = 'relu'
ReLU.Settings = false
Tanh.Settings = false
GeLU.Settings = true



[Training-Settings.learning-objective]

bias = true   # learning objectives: bias = ground-based species observation - geophysical species concentration estimation
normalize_bias = false
unit_normalize_bias = false
normalize_species = false
absolute_species  = false 
log_species = false


#########################################################################################################################################################

[Spatial-CrossValidation]

Combine_with_geophysical = true
Spatial_CrossValidation_Switch      = true
Spatial_CV_LossAccuracy_plot_Switch = true

[Spatial-CrossValidation.Training_Settings]

kfold   = 10
repeats = 1
beginyears = [2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]#,2020,2021,2022]
endyears   = [2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019]#,2020,2021,2022]

training_area = 'GL'
Test_Areas    = ['GL','NA','AS','EU']
MultiyearForMultiAreasList = [['NA'],['NA'],['NA'],['NA'],['NA'],['NA'],['NA'],['NA'],['NA'],['NA'],['NA','EU'],['NA','EU'],['NA','EU'],['NA','EU'],['NA','EU'],['NA','EU','AS','GL'],['NA','EU','AS','GL'],['NA','EU','AS','GL'],['NA','EU','AS','GL'],['NA','EU','AS','GL']]#,['NA','EU','AS','GL'],['NA','EU','AS','GL'],['NA','EU','AS','GL']]## Each model test on which areas

Area_beginyears.NA = 2001
Area_beginyears.EU = 2010
Area_beginyears.AS = 2015
Area_beginyears.GL = 2015

[Spatial-CrossValidation.Visualization_Settings]

regression_plot_switch = true

[Spatial-CrossValidation.Forced-Slope-Unity]

ForcedSlopeUnity = false # True: force the slope to unity and offset to zero with Training datasets
EachMonthForcedSlopeUnity = true # True: force the slope to unity and offset to zero by each year, each month; False: by each month, but all-year average 

